apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-deploment
  labels:
    app: card-api
  annotations:
spec:
  selector:
    matchLabels:
      app: card-api
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          app: card-api
        spec:
          containers:
          - name: card-api
            image: lostio/cardapi:1.0.0
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "512Mi"
                cpu: "500m"
              